ARC-Seal: i=1; cv=none; a=rsa-sha256; d=dmarced.com; s=arc; t=1497905898;
 b=FqACbo0E41uaLEWDJlIfyeM6hGmZRfJOC3obvdaEjIWHOlPUmfHSSl5aZ9u6Y1
 zTGxOJkG+yWNCURehzw70VFFvY/hJ84E3HsqM0Kk7Ba3TS1r1omOS2hoUInb2YN0
 /VKPiyRHzKZmZ6hlpraXErlgmLcyXNDQphhu1200w32qg=
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed;
 d=dmarced.com; s=arc; t=1497905898; h=mime-version
 : from : date : message-id : subject : to :
 content-type : from : date : subject;
 bh=0CXa+8KdEdT/woyATPDyemCrV8UCRAzMncskEMwihOs=;
 b=eoa8X/yDwVDOf3pB2ER/Q4C5hDDCMyiYTz4Q+m3FQJMSBdmNy
 sX0Owq5rHumNKLqDe+AA2g7zfCVWyIR1NGa7TsgdQ6QXUWfMaDC
 zym0r+KthDium4LaD+ua4cpATZfdNnjj2N5Wmghz7pbPDhfapOX
 RItMVzLAJrPemLDQeurw=
ARC-Authentication-Results: i=1; dmarced.com: none
MIME-Version: 1.0
Received: by 10.200.43.27 with HTTP; Thu, 15 Jun 2017 15:31:48 -0700 (PDT)
From: Seth Blank <seth@valimail.com>
Date: Thu, 15 Jun 2017 23:31:48 +0100
Message-ID: <CAOZAAfMEAMYDSCGoETtc_Pyd3XNC4a5BmaUpx1mWwgC5KO1fdw@mail.gmail.com>
Subject: this message fails openarc
To: Gene Shuman <gene@valimail.com>
Content-Type: multipart/alternative; boundary="001a113d4df63564fe0552073d54"

--001a113d4df63564fe0552073d54
Content-Type: text/plain; charset="UTF-8"

-Seth

-- 

[image: logo for sig file.png]

Bringing Trust to Email

Seth Blank | Head of Product for Open Source and Protocols
seth@valimail.com
+1-415-894-2724 <415-894-2724>

--001a113d4df63564fe0552073d54
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">-Seth<br clear=3D"all"><div><br></div>-- <br><div class=3D=
"gmail_signature" data-smartmail=3D"gmail_signature"><div dir=3D"ltr"><div>=
<div dir=3D"ltr"><div><div dir=3D"ltr"><p dir=3D"ltr" style=3D"font-size:12=
.8px;line-height:1.38;margin-top:0pt;margin-bottom:0pt"><span style=3D"font=
-size:14.6667px;font-family:Arial;color:rgb(0,0,0);vertical-align:baseline;=
white-space:pre-wrap;background-color:transparent"><img src=3D"https://lh5.=
googleusercontent.com/2H5o4IUaWTQg0CyrwoJc9mFj0TcbJMMCWaIZWc5tSI-3Y7NtaSXWV=
Y5jyaxa8eEuXkbx_liH2_QV_IcQWNAs2nN07sRNDvA5OSd06XWJiIcMKW24c8dRvUh4xr33iC_C=
MgHzgODr" width=3D"239" height=3D"61" alt=3D"logo for sig file.png" style=
=3D"border:none"></span></p><p dir=3D"ltr" style=3D"font-size:12.8px;line-h=
eight:1.38;margin-top:0pt;margin-bottom:0pt"><span style=3D"font-size:12px;=
font-family:Calibri;color:rgb(131,137,128);font-style:italic;vertical-align=
:baseline;white-space:pre-wrap">Bringing Trust to Email</span></p><p dir=3D=
"ltr" style=3D"font-size:12.8px;line-height:1.38;margin-top:0pt;margin-bott=
om:0pt"><span style=3D"font-size:14px;color:rgb(131,137,128);vertical-align=
:baseline;white-space:pre-wrap"><font face=3D"arial, helvetica, sans-serif"=
>Seth Blank | Head of Product </font></span><font color=3D"#838980" face=3D=
"arial, helvetica, sans-serif"><span style=3D"font-size:14px;white-space:pr=
e-wrap">for Open Source and Protocols</span></font></p><span style=3D"font-=
family:arial,helvetica,sans-serif;font-size:14px;white-space:pre-wrap"><a h=
ref=3D"mailto:seth@valimail.com" target=3D"_blank">seth@valimail.com</a></s=
pan><font color=3D"#838980" face=3D"arial, helvetica, sans-serif" style=3D"=
font-size:12.8px"><span style=3D"font-size:14px;white-space:pre-wrap"><br><=
/span></font><span style=3D"font-size:14px;white-space:pre-wrap"><font face=
=3D"arial, helvetica, sans-serif"><a href=3D"tel:415-894-2724" target=3D"_b=
lank">+1-415-894-2724</a></font></span><br></div></div></div></div></div></=
div>
</div>

--001a113d4df63564fe0552073d54--